name:                quickcheck-demo
version:             0.1.0.0
github:              "githubuser/quickcheck-demo"
license:             MIT
author:              "Muhammad Tabaza"
maintainer:          "muhammadtabaza@gmail.com"
copyright:           "2019 Muhammad Tabaza"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/quickcheck-demo#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck

library:
  source-dirs: src

executables:
  quickcheck-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quickcheck-demo

tests:
  quickcheck-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quickcheck-demo
